[package]
name = "wizhle"
version = "0.1.0"
edition = "2021"
authors = ["JereyBeni"]
description = "Experimental High-Level Emulator (HLE) for Samsung TouchWiz Android UI"
license = "MIT"
repository = "https://github.com/JereyBeni/WizHLE"

[dependencies]
log = "0.4"
env_logger = "0.11"
eframe = "0.29"
egui = "0.29"

[profile.release]
lto = true
codegen-units = 1
